/**
 * YouTube 字幕（timedtext）的解析与取值。
 *
 * 这里的每一条规则都来自实测，而不是文档——YouTube 没有为这些接口发布文档，
 * 而它们近一年动过好几次。凡是"猜"出来的字段名，坏掉时都是静默的。
 */

/** 一条字幕：起止时间与文本。 */
export interface Cue {
  /** 毫秒。 */
  startMs: number
  /** 毫秒。缺失时由下一条的起点推出，见 `parseJson3`。 */
  endMs: number
  text: string
}

interface Json3Seg {
  utf8?: string
  /** 逐词时间偏移，自动字幕才有。 */
  tOffsetMs?: number
  /** ASR 置信度。 */
  acAsrConf?: number
  /** 说话人切换，出现在部分多人视频里。 */
  isSpeakerChange?: number
}

interface Json3Event {
  tStartMs?: number
  /**
   * 可选。实测三个视频分别有 99 / 8 / 7 个事件没有这个字段，
   * 全部是 `aAppend` 换行事件。当成必填会在这些事件上算出 NaN。
   */
  dDurationMs?: number
  /** 值为 1 时是纯换行事件，segs 恒为 [{utf8:"\n"}]，不是一条字幕。 */
  aAppend?: number
  segs?: Json3Seg[]
}

export interface Json3Response {
  events?: Json3Event[]
}

/** 一条字幕轨。字段来自 `playerResponse.captions.playerCaptionsTracklistRenderer`。 */
export interface CaptionTrack {
  baseUrl: string
  languageCode: string
  /** 仅自动生成轨才有这个字段，值为 'asr'；人工轨上**不存在**而不是空串。 */
  kind?: string
  name?: { simpleText?: string; runs?: Array<{ text?: string }> }
  vssId?: string
  isTranslatable?: boolean
}

/**
 * 轨道名。
 *
 * 两种形态不是随机的：页面内的 player response 恒为 `simpleText`，
 * 而 ANDROID/IOS 客户端恒为 `runs`。只处理一种会在另一条路径上拿到空字符串。
 */
export function trackLabel(track: CaptionTrack): string {
  const name = track.name
  if (!name) return track.languageCode
  if (typeof name.simpleText === 'string' && name.simpleText) return name.simpleText
  const runs = name.runs ?? []
  const joined = runs.map((run) => run.text ?? '').join('')
  return joined || track.languageCode
}

/** 自动生成的字幕。用 `kind === 'asr'` 判断——人工轨没有这个字段，`.includes` 会抛错。 */
export function isAutoGenerated(track: CaptionTrack): boolean {
  return track.kind === 'asr'
}

/**
 * 把字幕地址补成"能真正取到内容"的样子。
 *
 * 三件事，缺一条就静默失败：
 *
 * 1. **`fmt` 必须用 set 而不是字符串拼接。** 部分来源返回的 baseUrl 末尾已经烤了
 *    `&fmt=srv3`，再拼一个 `&fmt=json3` 不会生效（同名参数取第一个），拿回来的是
 *    一份 XML，而解析器只会得到零条字幕。
 * 2. **`pot` 与 `c=WEB` 要同时带。** 隔离变量实测：只带 pot → 200/0 字节；
 *    只带 c=WEB → 200/0；两者都带 → 200/46010。少任何一个都是空 body，
 *    而且没有错误码。
 * 3. **删掉 `xosf`。** 它会让 json3/srv3 的位置数据出错。
 */
export function buildTimedTextUrl(baseUrl: string, options: { pot?: string } = {}): string {
  const url = new URL(baseUrl)
  url.searchParams.set('fmt', 'json3')
  url.searchParams.delete('xosf')
  if (options.pot) {
    url.searchParams.set('pot', options.pot)
    url.searchParams.set('potc', '1')
    url.searchParams.set('c', 'WEB')
  }
  return url.toString()
}

/** `baseUrl` 上带 `exp=xpe` 或 `xpv` 时，不带 pot 一定拿到空 body。 */
export function requiresProofOfOrigin(baseUrl: string): boolean {
  try {
    const exp = new URL(baseUrl).searchParams.get('exp') ?? ''
    return exp.includes('xpe') || exp.includes('xpv')
  } catch {
    return false
  }
}

/**
 * YouTube 在被打得太频繁时不返回 429，而是返回 200 加一张反爬 HTML 页。
 * 不识别它的话，JSON.parse 会抛出一个和真实原因毫无关系的错误。
 */
export function looksLikeBlockPage(body: string): boolean {
  const head = body.slice(0, 400).toLowerCase()
  return head.trimStart().startsWith('<') && (head.includes('sorry') || head.includes('unusual traffic'))
}

/**
 * json3 → 字幕数组。
 *
 * 关于自动字幕，实测纠正了一个流传的说法：json3 的 ASR **不是**滚动重复的
 * （1955 条 cue 里相邻完全相同 0 对、相邻互为子串 0 对）。所以这里不做"合并重复行"——
 * 那个操作在真实数据上只会把正常字幕改坏。滚动重复是 srv3/vtt 的特征，不是 json3 的。
 */
export function parseJson3(payload: Json3Response): Cue[] {
  const events = payload.events ?? []
  const cues: Cue[] = []

  for (const event of events) {
    // 纯换行事件：它标记的是断行，不是一条字幕。
    if (event.aAppend === 1) continue
    if (typeof event.tStartMs !== 'number') continue

    const text = (event.segs ?? [])
      .map((seg) => seg.utf8 ?? '')
      .join('')
      .replace(/\s+/g, ' ')
      .trim()
    if (!text) continue

    const duration = typeof event.dDurationMs === 'number' ? event.dDurationMs : 0
    cues.push({ startMs: event.tStartMs, endMs: event.tStartMs + duration, text })
  }

  cues.sort((a, b) => a.startMs - b.startMs)

  // 缺时长的（以及时长为 0 的）用下一条的起点收尾；最后一条给一个保守的默认值。
  for (let index = 0; index < cues.length; index++) {
    const cue = cues[index]!
    if (cue.endMs > cue.startMs) continue
    const next = cues[index + 1]
    cue.endMs = next ? next.startMs : cue.startMs + 3000
  }

  return cues
}

/**
 * 当前时刻对应的字幕下标，找不到返回 -1。
 *
 * 二分而不是线性扫：一小时的视频有上千条字幕，而这个函数每一帧都会被调用一次。
 */
export function cueIndexAt(cues: Cue[], timeMs: number): number {
  let low = 0
  let high = cues.length - 1
  let found = -1

  while (low <= high) {
    const mid = (low + high) >> 1
    const cue = cues[mid]!
    if (timeMs < cue.startMs) {
      high = mid - 1
    } else if (timeMs >= cue.endMs) {
      low = mid + 1
    } else {
      found = mid
      break
    }
  }
  return found
}
