import { describe, expect, it } from 'vitest'
import {
  buildTimedTextUrl,
  cueIndexAt,
  isAutoGenerated,
  looksLikeBlockPage,
  parseJson3,
  requiresProofOfOrigin,
  trackLabel,
  type CaptionTrack,
} from './timedtext.ts'

/**
 * 每条断言对应一个实测结论。YouTube 这些接口没有文档，猜错字段名时的表现是
 * 「一切正常，只是没有字幕」——所以这些测试是这一层唯一的说明书。
 */

const SIGNED =
  'https://www.youtube.com/api/timedtext?v=abc&exp=xpe&signature=s&expire=1&xosf=1&fmt=srv3'

describe('字幕地址', () => {
  it('用 set 覆盖已经烤在地址里的 fmt', () => {
    // 字符串拼接在这里是无效的：同名参数取第一个，拿回来的会是一份 XML。
    const url = new URL(buildTimedTextUrl(SIGNED))
    expect(url.searchParams.getAll('fmt')).toEqual(['json3'])
  })

  it('删掉 xosf——它会让 json3 的位置数据出错', () => {
    expect(new URL(buildTimedTextUrl(SIGNED)).searchParams.has('xosf')).toBe(false)
  })

  it('pot 与 c=WEB 必须同时出现', () => {
    // 隔离变量实测：只带其中一个都是 200 + 空 body，且没有错误码。
    const url = new URL(buildTimedTextUrl(SIGNED, { pot: 'TOKEN' }))
    expect(url.searchParams.get('pot')).toBe('TOKEN')
    expect(url.searchParams.get('c')).toBe('WEB')
    expect(url.searchParams.get('potc')).toBe('1')
  })

  it('没有 pot 时不会凭空加上 c=WEB', () => {
    const url = new URL(buildTimedTextUrl(SIGNED))
    expect(url.searchParams.has('c')).toBe(false)
  })

  it('从 exp 参数认出「必须带 pot」', () => {
    expect(requiresProofOfOrigin(SIGNED)).toBe(true)
    expect(requiresProofOfOrigin('https://x.test/api/timedtext?v=a&exp=xpv')).toBe(true)
    expect(requiresProofOfOrigin('https://x.test/api/timedtext?v=a')).toBe(false)
    expect(requiresProofOfOrigin('not a url')).toBe(false)
  })
})

describe('反爬页', () => {
  it('认出 200 + HTML 的限流页，而不是让 JSON.parse 报一个无关的错', () => {
    expect(looksLikeBlockPage('<!DOCTYPE html><html><title>Sorry...</title>')).toBe(true)
    expect(looksLikeBlockPage('  <html>detected unusual traffic from your network')).toBe(true)
    expect(looksLikeBlockPage('{"events":[]}')).toBe(false)
  })
})

describe('轨道信息', () => {
  it('两种 name 形态都取得到——它们按客户端分布，不是随机的', () => {
    const web: CaptionTrack = { baseUrl: '', languageCode: 'en', name: { simpleText: 'English' } }
    const mobile: CaptionTrack = {
      baseUrl: '',
      languageCode: 'en',
      name: { runs: [{ text: 'English ' }, { text: '(auto)' }] },
    }
    expect(trackLabel(web)).toBe('English')
    expect(trackLabel(mobile)).toBe('English (auto)')
    expect(trackLabel({ baseUrl: '', languageCode: 'de-DE' })).toBe('de-DE')
  })

  it('人工轨没有 kind 字段，判断时不能崩', () => {
    expect(isAutoGenerated({ baseUrl: '', languageCode: 'en' })).toBe(false)
    expect(isAutoGenerated({ baseUrl: '', languageCode: 'en', kind: 'asr' })).toBe(true)
  })
})

describe('json3 解析', () => {
  it('跳过 aAppend 换行事件——它标记断行，不是一条字幕', () => {
    const cues = parseJson3({
      events: [
        { tStartMs: 0, dDurationMs: 1000, segs: [{ utf8: 'Hello' }] },
        { tStartMs: 500, aAppend: 1, segs: [{ utf8: '\n' }] },
        { tStartMs: 1000, dDurationMs: 1000, segs: [{ utf8: 'world' }] },
      ],
    })
    expect(cues.map((cue) => cue.text)).toEqual(['Hello', 'world'])
  })

  it('把 segs 拼成一句，并归一空白', () => {
    const cues = parseJson3({
      events: [
        {
          tStartMs: 0,
          dDurationMs: 900,
          segs: [{ utf8: 'binding ' }, { utf8: 'to\n a ' }, { utf8: 'target' }],
        },
      ],
    })
    expect(cues[0]!.text).toBe('binding to a target')
  })

  it('dDurationMs 缺失时用下一条的起点收尾', () => {
    // 实测有事件确实没有这个字段；当成必填会算出 NaN，整条字幕永远匹配不上。
    const cues = parseJson3({
      events: [
        { tStartMs: 0, segs: [{ utf8: 'first' }] },
        { tStartMs: 2500, dDurationMs: 1000, segs: [{ utf8: 'second' }] },
      ],
    })
    expect(cues[0]!.endMs).toBe(2500)
    expect(Number.isNaN(cues[0]!.endMs)).toBe(false)
  })

  it('丢弃没有文本的事件', () => {
    const cues = parseJson3({
      events: [
        { tStartMs: 0, dDurationMs: 100, segs: [] },
        { tStartMs: 100, dDurationMs: 100 },
        { tStartMs: 200, dDurationMs: 100, segs: [{ utf8: '   ' }] },
        { tStartMs: 300, dDurationMs: 100, segs: [{ utf8: 'real' }] },
      ],
    })
    expect(cues).toHaveLength(1)
  })

  it('保留自动字幕里相邻的重复措辞，不做「去重」', () => {
    /*
     * 实测：json3 的 ASR 相邻重复为 0 对。所谓「滚动重复」是 srv3/vtt 的特征。
     * 在 json3 上做合并只会把说话人真的重复了两次的句子改坏。
     */
    const cues = parseJson3({
      events: [
        { tStartMs: 0, dDurationMs: 500, segs: [{ utf8: 'No no' }] },
        { tStartMs: 500, dDurationMs: 500, segs: [{ utf8: 'No no' }] },
      ],
    })
    expect(cues.map((cue) => cue.text)).toEqual(['No no', 'No no'])
  })

  it('保留说话人切换等额外字段的事件文本', () => {
    const cues = parseJson3({
      events: [
        { tStartMs: 0, dDurationMs: 500, segs: [{ utf8: 'Exactly.', acAsrConf: 0, isSpeakerChange: 1 }] },
      ],
    })
    expect(cues[0]!.text).toBe('Exactly.')
  })
})

describe('按时间取字幕', () => {
  const cues = [
    { startMs: 0, endMs: 1000, text: 'a' },
    { startMs: 1000, endMs: 2000, text: 'b' },
    { startMs: 5000, endMs: 6000, text: 'c' },
  ]

  it('落在区间内', () => {
    expect(cueIndexAt(cues, 0)).toBe(0)
    expect(cueIndexAt(cues, 999)).toBe(0)
    expect(cueIndexAt(cues, 1000)).toBe(1)
    expect(cueIndexAt(cues, 5500)).toBe(2)
  })

  it('落在空隙或两端之外时明确返回 -1，而不是最近的一条', () => {
    // 静默地显示上一句，会让字幕在无人说话时挂着不动。
    expect(cueIndexAt(cues, 3000)).toBe(-1)
    expect(cueIndexAt(cues, 6000)).toBe(-1)
    expect(cueIndexAt([], 0)).toBe(-1)
  })
})
