import { t } from '@/i18n/index.ts'
import { isAutoGenerated, trackLabel, type CaptionTrack } from './timedtext.ts'

/**
 * 从一堆字幕轨里挑出该翻译的那一条。
 *
 * 一个视频常有二三十条轨——原语言的人工轨、自动生成轨，以及 YouTube 自己机翻出来的
 * 一堆语言。挑错了不会报错，只会安静地翻译一条你不想要的轨，所以规则写在这里并有测试。
 *
 * 优先级，从高到低：
 *
 * 1. **用户指定的源语言**的人工轨——人工字幕有标点和大小写，翻译质量明显更好。
 * 2. 用户指定源语言的自动生成轨。
 * 3. 视频默认轨（清单里的第一条），人工优先。
 *
 * **不选目标语言的轨。** 如果视频已经有中文轨，那读者根本不需要我们；
 * 而把中文轨再翻成中文，正是整页翻译那次翻车的同一个错误。
 */
export interface TrackChoice {
  track: CaptionTrack
  /** 为什么选它——出现在界面上，让"翻的不是我要的那条"变成可诊断的。 */
  reason: string
}

/** `en-US`、`zh-Hans` 这类都归到主语言上比较。 */
function primary(code: string): string {
  return (code || '').split('-')[0]!.toLowerCase()
}

/**
 * 理由这句话里只有"（自动生成）"是我们说的——轨道名是 YouTube 给的，照原样带过去。
 *
 * 在函数里取文案而不是在模块顶层：内容脚本随页面加载一次，顶层取值会把语言
 * 钉死在那一刻，读者之后改设置就再也不生效。
 */
function reasonFor(track: CaptionTrack): string {
  const label = trackLabel(track)
  return isAutoGenerated(track) ? t('video.track.auto_generated', { label }) : label
}

export function chooseTrack(
  tracks: CaptionTrack[],
  options: { sourceLanguage?: string; targetLanguage: string },
): TrackChoice | null {
  const usable = tracks.filter((track) => track.baseUrl)
  if (usable.length === 0) return null

  const target = primary(options.targetLanguage)
  const wanted = options.sourceLanguage && options.sourceLanguage !== 'auto'
    ? primary(options.sourceLanguage)
    : ''

  const notTarget = usable.filter((track) => primary(track.languageCode) !== target)
  /*
   * 只剩目标语言的轨时，宁可不翻。
   * 把中文字幕再翻一遍中文，是"看起来在工作、实际上在破坏"的那类失败。
   */
  if (notTarget.length === 0) return null

  const pick = (list: CaptionTrack[]) =>
    list.find((track) => !isAutoGenerated(track)) ?? list[0]

  if (wanted) {
    const inWanted = notTarget.filter((track) => primary(track.languageCode) === wanted)
    const chosen = pick(inWanted)
    if (chosen) {
      return { track: chosen, reason: reasonFor(chosen) }
    }
  }

  const chosen = pick(notTarget)!
  return { track: chosen, reason: reasonFor(chosen) }
}
